# Generated by Django 5.2.3 on 2026-02-18 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachineCategory',
        ),
    ]
