# Generated by Django 5.2.3 on 2026-02-18 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='MachineImage/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wadmin.machinecategory')),
            ],
            options={
                'db_table': 'tbl_machine',
            },
        ),
    ]
