# Generated by Django 5.2.3 on 2026-02-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0006_machine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_announcement',
            },
        ),
    ]
