# Generated by Django 5.2.3 on 2026-02-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0007_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
