# Generated by Django 5.2.11 on 2026-02-22 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0008_alter_announcement_id_alter_machine_id_and_more'),
        ('wadmin', '0009_machine'),
    ]

    operations = [
    ]
