# Generated by Django 5.2.3 on 2026-02-28 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0011_alter_announcement_id_alter_machine_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
