# Generated by Django 5.2.3 on 2026-03-01 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wadmin', '0013_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
