# Generated by Django 6.0.2 on 2026-02-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('employeid', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='UserPhoto/')),
                ('password', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'tbl_user',
            },
        ),
    ]
