# Generated by Django 5.2.3 on 2026-02-19 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0003_alter_admin_id_alter_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
