# Generated by Django 5.2.3 on 2026-02-19 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
