# Generated by Django 5.2.3 on 2026-02-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0006_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('employeid', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('gender', models.CharField(max_length=50)),
                ('photo', models.FileField(blank=True, null=True, upload_to='AdminPhoto/')),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tbl_admin',
            },
        ),
    ]
