# Generated by Django 5.2.11 on 2026-02-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0008_user_status_alter_admin_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
