# Generated by Django 5.2.3 on 2026-03-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0010_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(max_length=10)),
                ('sender_id', models.IntegerField()),
                ('receiver_type', models.CharField(max_length=10)),
                ('receiver_id', models.IntegerField()),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tbl_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
