# Generated by Django 5.2.3 on 2026-02-22 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0009_alter_admin_id_alter_user_id'),
        ('wadmin', '0011_alter_announcement_id_alter_machine_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMachineFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='UserMachineFiles/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wadmin.machine')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.user')),
            ],
            options={
                'db_table': 'tbl_machine_file',
            },
        ),
    ]
